### PR TITLE
Add authentication for system_restore_post

### PR DESCRIPTION
**Pull request by robin-nitrokey**
This patch fixes the API spec to add authentication to the `POST /system/restore` endpoint.

Fixes: https://github.com/Nitrokey/nethsm-sdk-rs/issues/15

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
@dvzrv Can you please test if this fixes your issue?

**Comment by jans23** [comment]
Shouldn't the OpenAPI spec be fixed in the original `nethsm` repo instead?

**Comment by robin-nitrokey** [comment]
@jans23 Yes, but this PR allows us to test the changes before it is fixed upstream.

**Comment by dvzrv** [comment]
Without this change I get:

```
error: nethsm::Error - NetHSM API error: Restoring backup failed: Deseralization error (no message in body) (status code 401)
```

With this change I get:

```
error: nethsm::Error - NetHSM API error: Restoring backup failed: Body cannot be empty. (status code 400)
```

I am running restore against an "operational" container.

While the authentication error appears gone, I don't really know what to do about the 400, which is documented as
> Bad request - restore did not apply.

**Comment by dvzrv** [comment]
I am also getting a 400 when trying to restore an "unprovisioned" container from backup.

**Comment by dvzrv** [comment]
Um, `backup_file` appears to be entirely unused in `system_restore_post`?!

**Comment by robin-nitrokey** [comment]
It looks like we missed the code path for multi-part requests when replacing `reqwest` with `ureq` in https://github.com/Nitrokey/nethsm-sdk-rs/pull/1.  Let’s handle that in a different issue: https://github.com/Nitrokey/nethsm-sdk-rs/issues/20.

**Comment by ansiwen** [comment]
FWIW: we implemented multipart after we changed to ureq, but  because we only used the Rust SDK for the PKCS#11 module, which doesn't handle restore or updates, we didn't care. 😉

**Pull request merged**
